Don't set LC_ALL=C during build as that breaks python apps
Setting LC_ALL=C breaks python apps doing I/O on UTF-8 source
files. In particular this broke glib-mkenums

    Traceback (most recent call last):
      File "/usr/bin/glib-mkenums", line 669, in <module>
        process_file(fname)
      File "/usr/bin/glib-mkenums", line 406, in process_file
        line = curfile.readline()
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 849: ordinal not in range(128)

Signed-off-by: Daniel P. Berrange <berrange@redhat.com>